vich_uploader:
    db_driver: orm

    mappings:
        relatoriospush:
            uri_prefix: /uploads/relatoriospush
            upload_destination: '%kernel.project_dir%/public/uploads/relatoriospush'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
