vich_uploader:
    db_driver: orm

    mappings:
        relatoriospush:
            uri_prefix: /uploads/relatoriospush
            upload_destination: '%kernel.project_dir%/public/uploads/relatoriospush'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        produto_imagem:
            uri_prefix: /images/produtos
            upload_destination: '%env(PASTA_FOTOS_PRODUTOS)%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: app.utils.estoque.vich_uploader_produto_directory_namer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
